version: '3.8'

services:
  backend:
    image: todo-backend
    build: .
    ports:
      - 3000:3000
    environment:
      MONGO_URL: mongodb://root:example@localhost:3456/the_database
      REDIS_URL: redis://localhost:6379